pathToSourceCSV:
  "/Users/skuranov"
nameOfSourceCSV:
  "jcpenney_com-ecommerce_sample"

spring:
  application:
    name:
      "catalog-service"
  zipkin:
    base-url: "http://localhost:9411/"
  sleuth:
    sampler:
      probability: 1

logging:
  level:
    root: TRACE

eureka:
  client:
    service-url:
      defaultZone:
        "http://localhost:8761/eureka/"

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    metrics:
      enabled: true